// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmrhljjfmxropvguzlbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtcmhsampmbXhyb3B2Z3V6bGJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNDIxNzMsImV4cCI6MjA3NDYxODE3M30.rw0anN3X9WhKGm39PEHFiP7qawgmSGuhWvbfqsmUjxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});